### PR TITLE
TOTEMX 0.1

### PR DESCRIPTION
**Pull request by azhizhinov**
Hello.
Can be useful. Totally untested.
Stay safe.

### CODE REVIEW

**Comment by GEIGEIGEIST** [comment]
Could you give me a bit more context?

**Comment by azhizhinov** [comment]
Hello.
MX version of TOTEM.
Some footprints were borrowed from wj-zhe/Kretstrad, kriku/kpukboard-pcb and mmccoyd/hillside projects.
20230518 AZHIZHINOV TOTEMX 01

20230518 AZHIZHINOV TOTEMX 00

**Comment by GEIGEIGEIST** [comment]
Oh that's great! I'm happy to link it if you put it in your own repo, but since it's basically an own board, which I didn't made I wouldn't add it to the main repo, since people would ask me for support to a board I didn't make.

**Comment by azhizhinov** [comment]
Ok. May be later.

**Comment by azhizhinov** [comment]
Hello.
So, I've published the sources.
https://github.com/azhizhinov/TOTEMX
Have a nice day.

**Pull request closed without merging**
